export const UI_CONSTANTS = {
  COMMON: {
    LOADING: "Loading...",
    SAVING: "Saving...",
    CANCEL: "Cancel",
    EDIT: "Edit",
    DELETE: "Delete",
    VIEW: "View Details",
    ACTIONS: "Actions",
    RETIRE: "Retire",
    CLOSE: "Close",
    DISPATCH: "Dispatch",
    COMPLETE: "Complete",
    COMPLETING: "Completing...",
    DISPATCHING: "Dispatching...",
    SAVE_DRAFT: "Save Draft",
    SUBMITTING: "Submitting...",
    CONFIRM_DELETE: "Are you sure you want to delete this?",
    UNEXPECTED_ERROR: "An unexpected error occurred",
  },
  AUTH: {
    SIGN_IN_TITLE: "Sign in",
    SIGN_IN_SUBTITLE: "Access your dashboard with your email and password.",
    EMAIL_LABEL: "Email",
    PASSWORD_LABEL: "Password",
    EMAIL_PLACEHOLDER: "name@example.com",
    PASSWORD_PLACEHOLDER: "Enter your password",
    SIGN_IN_BUTTON: "Sign in",
    SIGNING_IN_BUTTON: "Signing in...",
    WELCOME_BACK: "Welcome back",
    VALIDATION: {
      EMAIL_INVALID: "Please enter a valid email address.",
      PASSWORD_REQUIRED: "Password is required.",
    },
  },
  LAYOUT: {
    BRAND: "FleetOS",
    LOGOUT: "Logout",
    USER_ROLE_BADGE: "Role: ",
    THEME_LIGHT: "Light Theme",
    THEME_DARK: "Dark Theme",
    SIDEBAR: {
      DASHBOARD: "Dashboard Overview",
      VEHICLES: "Vehicles Fleet",
      DRIVERS: "Drivers Roster",
      TRIPS: "Trips & Dispatch",
      MAINTENANCE: "Maintenance Logs",
      FUEL_AND_EXPENSES: "Fuel & Expenses",
      ANALYTICS: "Fleet Analytics",
      SETTINGS: "System Settings",
    },
  },
  VEHICLES: {
    HEADER_TITLE: "Vehicles Fleet",
    HEADER_SUBTITLE: "Manage your operations fleet, track capacities, and vehicle status.",
    ADD_VEHICLE: "Add Vehicle",
    SEARCH_PLACEHOLDER: "Search reg. no...",
    FILTER_TYPE: "Type:",
    FILTER_STATUS: "Status:",
    ALL_TYPES: "All Types",
    ALL_STATUSES: "All Statuses",
    TABLE_REG_NO: "Reg. No. (Unique)",
    TABLE_NAME: "Name/Model",
    TABLE_TYPE: "Type",
    TABLE_CAPACITY: "Capacity",
    TABLE_ODOMETER: "Odometer",
    TABLE_ACQ_COST: "Acq. Cost",
    TABLE_STATUS: "Status",
    TABLE_ACTIONS: "Actions",
    LOADING_TEXT: "Loading fleet...",
    NO_VEHICLES: "No vehicles found matching the filters.",
    FOOTER_RULE: "Rule: Registration No. must be unique • Retired/In Shop vehicles are hidden from Trip Dispatcher",
    ADD_TITLE: "Add New Vehicle",
    ADD_DESC: "Enter vehicle registration details, capacities, and acquisition cost.",
    EDIT_TITLE: "Edit Vehicle",
    EDIT_DESC: "Update the vehicle registration, details, or operational status.",
    DETAILS_TITLE: "Vehicle Details",
    DETAILS_DESC: "Full operational specifications and status details for the fleet vehicle.",
    DELETE_TITLE: "Retire Vehicle",
    DELETE_DESC: "Are you sure you want to retire this vehicle? This action is permanent and will hide it from the active trip dispatcher.",
    TOAST_LOAD_FAIL: "Failed to load vehicles",
    TOAST_ADD_SUCCESS: "Vehicle added successfully",
    TOAST_ADD_FAIL: "Failed to create vehicle",
    TOAST_DETAILS_FAIL: "Failed to fetch vehicle details",
    TOAST_EDIT_SUCCESS: "Vehicle updated successfully",
    TOAST_EDIT_FAIL: "Failed to update vehicle",
    TOAST_RETIRE_SUCCESS: "Vehicle retired successfully",
    TOAST_RETIRE_FAIL: "Failed to retire vehicle",
    FIELDS: {
      REG_NUMBER: "Reg. Number",
      NAME_MODEL: "Name / Model",
      TYPE: "Type",
      REGION: "Region",
      CAPACITY: "Capacity (Kg)",
      ODOMETER: "Odometer (Km)",
      ACQ_COST: "Acq. Cost (₹)",
      STATUS: "Status",
    },
    VALIDATION: {
      REG_REQUIRED: "Registration number is required",
      NAME_REQUIRED: "Name/model is required",
      TYPE_REQUIRED: "Please select a vehicle type",
      CAPACITY_REQUIRED: "Capacity is required",
      CAPACITY_POSITIVE: "Capacity must be greater than 0",
      ODOMETER_REQUIRED: "Odometer is required",
      ODOMETER_NONNEGATIVE: "Odometer reading cannot be negative",
      COST_REQUIRED: "Acquisition cost is required",
      COST_POSITIVE: "Acquisition cost must be greater than 0",
      REGION_REQUIRED: "Region is required",
    },
  },
  DRIVERS: {
    HEADER_TITLE: "Drivers Roster",
    HEADER_SUBTITLE: "Manage drivers, contact profiles, safety ratings, and licensing states.",
    ADD_DRIVER: "Add Driver",
    SEARCH_PLACEHOLDER: "Search name, license...",
    TABLE_NAME: "Name",
    TABLE_LICENSE: "License No.",
    TABLE_CLASS: "Class",
    TABLE_CONTACT: "Contact No.",
    TABLE_SAFETY: "Safety Score",
    TABLE_EXPIRY: "License Expiry",
    TABLE_STATUS: "Status",
    TABLE_ACTIONS: "Actions",
    LOADING_TEXT: "Loading roster...",
    NO_DRIVERS: "No drivers found matching the filters.",
    FOOTER_RULE: "Rule: License validity is verified at dispatch • Suspended drivers cannot be assigned to trips",
    ADD_TITLE: "Add New Driver Profile",
    ADD_DESC: "Enter driver registry particulars, contact information, and license details.",
    EDIT_TITLE: "Edit Driver Profile",
    EDIT_DESC: "Update contact info, licensing details, safety metrics, or dispatch status.",
    DETAILS_TITLE: "Driver Profile Details",
    DETAILS_DESC: "Full personnel metadata, safety score history, and licensing specifications.",
    DELETE_TITLE: "Suspend Driver Profile",
    DELETE_DESC: "Are you sure you want to suspend this driver profile? Suspended drivers cannot be dispatched on trips.",
    TOAST_LOAD_FAIL: "Failed to load drivers",
    TOAST_ADD_SUCCESS: "Driver added successfully",
    TOAST_ADD_FAIL: "Failed to create driver",
    TOAST_DETAILS_FAIL: "Failed to fetch driver details",
    TOAST_EDIT_SUCCESS: "Driver profile updated successfully",
    TOAST_EDIT_FAIL: "Failed to update driver profile",
    TOAST_SUSPEND_SUCCESS: "Driver profile suspended successfully",
    TOAST_SUSPEND_FAIL: "Failed to suspend driver profile",
    LICENSE_EXPIRED_WARNING: "EXPIRED",
    FIELDS: {
      NAME: "Full Name",
      LICENSE_NUMBER: "License Number",
      LICENSE_CATEGORY: "License Category",
      LICENSE_EXPIRY: "License Expiry Date",
      CONTACT_NUMBER: "Contact Number",
      SAFETY_SCORE: "Safety Score (0-100)",
      STATUS: "Status",
    },
    VALIDATION: {
      NAME_REQUIRED: "Driver name is required",
      LICENSE_REQUIRED: "License number is required",
      LICENSE_CAT_REQUIRED: "License category is required",
      LICENSE_EXP_REQUIRED: "License expiry date is required",
      CONTACT_REQUIRED: "Contact number is required",
      SAFETY_REQUIRED: "Safety score is required",
      SAFETY_MIN: "Safety score cannot be less than 0",
      SAFETY_MAX: "Safety score cannot exceed 100",
      STATUS_REQUIRED: "Please select a valid status",
    },
  },
  TRIPS: {
    HEADER_TITLE: "Trips Dispatch",
    HEADER_SUBTITLE: "Plan cargo shipments, select available vehicles & drivers, and track lifecycle status.",
    CREATE_TRIP: "Create Trip",
    TABLE_TRIP_ID: "Trip ID",
    TABLE_ROUTE: "Route",
    TABLE_VEHICLE: "Vehicle",
    TABLE_DRIVER: "Driver",
    TABLE_CARGO: "Cargo Weight",
    TABLE_DISTANCE: "Distance",
    TABLE_STATUS: "Status",
    TABLE_ACTIONS: "Actions",
    LOADING_TEXT: "Loading trips...",
    NO_TRIPS: "No dispatch trips found. Create a new trip to start.",
    CREATE_TITLE: "Create Trip",
    CREATE_DESC: "Deploy a new cargo consignment. Only available vehicles and drivers can be dispatched.",
    COMPLETE_TITLE: "Complete Trip",
    COMPLETE_DESC: "Record the actual distance traversed and fuel metrics.",
    DETAILS_TITLE: "Trip Consignment Details",
    DETAILS_DESC: "Full operational breakdown and records for Trip Consignment.",
    CAPACITY_WARNING_TITLE: "Dispatch Blocked",
    CAPACITY_WARNING_EXCEEDED: "Capacity exceeded by",
    TOAST_LOAD_FAIL: "Failed to load trips list",
    TOAST_ENTITIES_FAIL: "Failed to fetch available vehicles/drivers options",
    TOAST_CREATE_SUCCESS_DISPATCHED: "Trip created and dispatched successfully",
    TOAST_CREATE_SUCCESS_DRAFT: "Trip draft created successfully",
    TOAST_CREATE_WARNING_DISPATCH_FAIL: "Trip created as Draft, but dispatch request failed",
    TOAST_CREATE_FAIL: "Failed to create trip",
    TOAST_DISPATCH_SUCCESS: "Trip dispatched successfully",
    TOAST_DISPATCH_FAIL: "Failed to dispatch trip",
    TOAST_CANCEL_SUCCESS: "Trip cancelled successfully",
    TOAST_CANCEL_FAIL: "Failed to cancel trip",
    TOAST_COMPLETE_SUCCESS: "Trip marked as Completed",
    TOAST_COMPLETE_FAIL: "Failed to complete trip",
    FIELDS: {
      SOURCE: "Source",
      DESTINATION: "Destination",
      VEHICLE: "Vehicle (Available Only)",
      DRIVER: "Driver (Available Only)",
      CARGO_WEIGHT: "Cargo Weight (Kg)",
      PLANNED_DISTANCE: "Planned Distance (Km)",
      ACTUAL_DISTANCE: "Actual Distance (Km)",
      FUEL_CONSUMED: "Fuel Consumed (Liters)",
      FUEL_COST: "Fuel Cost (₹)",
    },
    VALIDATION: {
      SOURCE_REQUIRED: "Source location is required",
      DEST_REQUIRED: "Destination location is required",
      VEHICLE_REQUIRED: "Vehicle selection is required",
      DRIVER_REQUIRED: "Driver selection is required",
      CARGO_REQUIRED: "Cargo weight is required",
      CARGO_POSITIVE: "Cargo weight must be greater than 0",
      PLANNED_DIST_REQUIRED: "Planned distance is required",
      PLANNED_DIST_POSITIVE: "Planned distance must be greater than 0",
      ACTUAL_DIST_REQUIRED: "Actual distance is required",
      ACTUAL_DIST_POSITIVE: "Actual distance must be greater than 0",
      POSITIVE_NUMBER: "Must be a positive number",
    },
  },
  MAINTENANCE: {
    HEADER_TITLE: "Maintenance Logs",
    HEADER_SUBTITLE: "Track workshop events, schedule service entries, and log vehicle maintenance costs.",
    LOG_SERVICE: "Log Service",
    FILTER_STATUS: "Status:",
    ALL_STATUSES: "All Statuses",
    TABLE_VEHICLE: "Vehicle",
    TABLE_DESC: "Description",
    TABLE_COST: "Cost",
    TABLE_DATE: "Service Date",
    TABLE_STATUS: "Status",
    TABLE_ACTIONS: "Actions",
    LOADING_TEXT: "Loading log registry...",
    NO_LOGS: "No maintenance log entries found matching the filters.",
    FOOTER_RULE: "Rule: Logged vehicles are marked 'In Shop' and automatically restored to 'Available' upon log closure.",
    ADD_TITLE: "Log Maintenance Event",
    ADD_DESC: "Create a new workshop log. Selected vehicle status transitions to 'In Shop'.",
    CLOSE_TITLE: "Close Workshop Log",
    CLOSE_DESC: "Are you sure you want to close this maintenance log? Selected vehicle status will restore to 'Available'.",
    TOAST_LOAD_FAIL: "Failed to load maintenance logs",
    TOAST_VEHICLES_FAIL: "Failed to fetch vehicle options",
    TOAST_ADD_SUCCESS: "Maintenance event logged successfully",
    TOAST_ADD_FAIL: "Failed to log maintenance event",
    TOAST_CLOSE_SUCCESS: "Maintenance event closed successfully",
    TOAST_CLOSE_FAIL: "Failed to close maintenance log",
    FIELDS: {
      VEHICLE: "Vehicle (Non-Retired Only)",
      DESC: "Description",
      COST: "Cost (₹)",
      START_DATE: "Start Date",
    },
    VALIDATION: {
      VEHICLE_REQUIRED: "Vehicle selection is required",
      DESC_REQUIRED: "Description is required",
      COST_REQUIRED: "Cost is required",
      COST_NONNEGATIVE: "Cost cannot be negative",
      DATE_REQUIRED: "Start date is required",
    },
  },
  FINANCE: {
    HEADER_TITLE: "Operational Finance",
    HEADER_SUBTITLE: "Track vehicle operational expenses, refueling logs, and operational spend summaries.",
    TABS: {
      FUEL: "Fuel Logs",
      OTHER: "Other Expenses",
    },
    LOG_FUEL: "Log Fuel",
    LOG_EXPENSE: "Log Expense",
    TABLE_VEHICLE: "Vehicle",
    TABLE_DATE: "Date",
    TABLE_LITERS: "Liters",
    TABLE_FUEL_COST: "Fuel Cost (₹)",
    TABLE_TYPE: "Type",
    TABLE_AMOUNT: "Amount (₹)",
    TABLE_NOTE: "Note/Description",
    LOADING_FUEL: "Loading fuel logs...",
    LOADING_EXPENSES: "Loading expense logs...",
    NO_FUEL: "No fuel logs recorded.",
    NO_EXPENSES: "No other expenses recorded.",
    TOTAL_OPERATIONAL_COST: "Total Operational Cost",
    OPERATIONAL_COST_DESC: "Aggregated sum of refueling costs and logged operational maintenance expenses.",
    LOG_FUEL_TITLE: "Log Refueling Entry",
    LOG_FUEL_DESC: "Record litrage and total cost details for a refueling event.",
    LOG_EXPENSE_TITLE: "Log Custom Expense",
    LOG_EXPENSE_DESC: "Record general tolls, maintenance services, or custom operational costs.",
    TOAST_LOAD_FUEL_FAIL: "Failed to load fuel logs",
    TOAST_LOAD_EXP_FAIL: "Failed to load expense logs",
    TOAST_SUMMARY_FAIL: "Failed to load operational cost summary",
    TOAST_VEHICLES_FAIL: "Failed to load vehicles list options",
    TOAST_ADD_FUEL_SUCCESS: "Fuel entry logged successfully",
    TOAST_ADD_FUEL_FAIL: "Failed to log fuel entry",
    TOAST_ADD_EXP_SUCCESS: "Expense logged successfully",
    TOAST_ADD_EXP_FAIL: "Failed to log expense",
    FIELDS: {
      VEHICLE: "Vehicle",
      LITERS: "Liters",
      COST: "Fuel Cost (₹)",
      DATE: "Date",
      TYPE: "Expense Type",
      AMOUNT: "Amount (₹)",
      NOTE: "Note / Description",
    },
    VALIDATION: {
      VEHICLE_REQUIRED: "Vehicle selection is required",
      LITERS_REQUIRED: "Liters count is required",
      LITERS_POSITIVE: "Liters must be greater than 0",
      COST_REQUIRED: "Cost is required",
      COST_POSITIVE: "Cost must be greater than 0",
      DATE_REQUIRED: "Date is required",
      TYPE_REQUIRED: "Expense type is required",
      AMOUNT_REQUIRED: "Amount is required",
      AMOUNT_POSITIVE: "Amount must be greater than 0",
    },
  },
  ANALYTICS: {
    HEADER_TITLE: "Operations Analytics",
    HEADER_SUBTITLE: "Evaluate operations, track fuel efficiency metrics, asset utilization rates, and ROI margins.",
    METRIC_FUEL_EFF: "Avg. Fuel Efficiency",
    METRIC_FUEL_EFF_UNIT: " km/L",
    METRIC_UTILIZATION: "Fleet Utilization",
    METRIC_UTILIZATION_DESC: "Active vehicles on dispatch trips vs. total available fleet.",
    METRIC_OPERATIONAL_COST: "Total Operational Cost",
    METRIC_OPERATIONAL_COST_DESC: "Sum of all logged fuel, maintenance, and misc expenses.",
    METRIC_ROI: "Avg. Vehicle ROI Metric",
    METRIC_ROI_DESC: "Average ratio of planned distance to acquisition cost.",
    CHART_TITLE: "Operating Cost Trend (MoM)",
    CHART_REFUELING: "Refueling",
    CHART_MAINTENANCE: "Maintenance",
    CHART_MISC: "Misc & Tolls",
    COSTLIEST_VEHICLES: "Top Costliest Vehicles to Maintain",
    COSTLIEST_VEHICLES_DESC: "Highest operational expense aggregates recorded per asset.",
    TOAST_LOAD_FAIL: "Failed to load analytics overview details",
    PROGRESS_RELATIVE_MARGIN: "Relative cost margin: ",
  },
  SETTINGS: {
    HEADER_TITLE: "System Settings",
    HEADER_SUBTITLE: "Manage depot configurations, currency settings, localization, and user role access levels.",
    TABS: {
      ORGANIZATION: "Organization Details",
      RBAC: "Access Control (RBAC)",
    },
    ORG_TITLE: "Organization Settings",
    ORG_DESC: "Set organization registry names, operational currencies, distance metrics, and default timezones.",
    RBAC_TITLE: "Role-Based Access Control",
    RBAC_DESC: "Manage fine-grained interface module permissions across system user accounts.",
    RBAC_TABLE_NAME: "User Account Name",
    RBAC_TABLE_EMAIL: "Email",
    RBAC_TABLE_ROLE: "System Role",
    RBAC_TABLE_MODULES: "Allowed Modules",
    RBAC_TABLE_ACTIONS: "Actions",
    RBAC_EDIT_TITLE: "Edit Access Permissions",
    RBAC_EDIT_DESC: "Update the role and allowed modules permissions for this user account.",
    TOAST_LOAD_ORG_FAIL: "Failed to load organization settings",
    TOAST_LOAD_RBAC_FAIL: "Failed to load RBAC permissions roster",
    TOAST_SAVE_ORG_SUCCESS: "Organization settings updated successfully",
    TOAST_SAVE_ORG_FAIL: "Failed to update organization settings",
    TOAST_SAVE_RBAC_SUCCESS: "Account access permissions updated successfully",
    TOAST_SAVE_RBAC_FAIL: "Failed to update account access permissions",
    FIELDS: {
      ORG_NAME: "Organization Name",
      DEPOT_NAME: "Depot Name",
      CURRENCY: "Currency Symbol",
      DISTANCE_UNIT: "Distance Metric Unit",
      TIMEZONE: "Depot Timezone",
      EMAIL: "Contact Email",
      PHONE: "Contact Phone Number",
      ADDRESS: "Depot Street Address",
      RBAC_ROLE: "Role Type",
      RBAC_MODULES: "Permitted Modules",
    },
    VALIDATION: {
      ORG_REQUIRED: "Organization name is required",
      DEPOT_REQUIRED: "Depot name is required",
      CURRENCY_REQUIRED: "Currency is required",
      TIMEZONE_REQUIRED: "Timezone is required",
      EMAIL_INVALID: "Please enter a valid contact email",
    },
  },
  DASHBOARD: {
    WELCOME_TITLE: "Welcome back, ",
    KPI_ACTIVE_TRIPS: "Active Trips",
    KPI_ACTIVE_TRIPS_DESC: "Consignments currently dispatched in progress.",
    KPI_ACTIVE_VEHICLES: "Active Vehicles",
    KPI_ACTIVE_VEHICLES_DESC: "Vehicles currently in service (On Trip).",
    KPI_MAINTENANCE: "In Workshop",
    KPI_MAINTENANCE_DESC: "Vehicles currently undergoing maintenance.",
    KPI_DRIVERS: "Active Drivers",
    KPI_DRIVERS_DESC: "Personnel currently dispatched on trips.",
    STATUS_TITLE: "Fleet Status Breakdown",
    TRIPS_TITLE: "Recent Dispatch Trips",
    TRIPS_DESC: "Quick overview of the latest cargo consignments logged in the system.",
    TOAST_LOAD_FAIL: "Failed to load dashboard overview data",
  },
} as const;
