import { Router } from 'express';
import { DriverStatus, ExpenseType, MaintenanceStatus, Prisma, Role, TripStatus, VehicleStatus } from '@prisma/client';
import { z } from 'zod';
import { prisma } from '../../config/prisma.js';
import { allowRoles } from '../../middlewares/auth.middleware.js';
import { asyncHandler } from '../../utils/asyncHandler.js';
import { ApiError } from '../../utils/ApiError.js';

export const operationsRouter = Router();
const all = Object.values(Role);
const vehicleInput = z.object({ registrationNumber: z.string().min(2), name: z.string().min(2), type: z.string().min(2), maxLoadCapacityKg: z.coerce.number().positive(), odometerKm: z.coerce.number().min(0).optional(), acquisitionCost: z.coerce.number().min(0), region: z.string().max(80).optional().nullable() });
const driverInput = z.object({ name: z.string().min(2), licenseNumber: z.string().min(2), licenseCategory: z.string().min(1), licenseExpiryDate: z.coerce.date(), contactNumber: z.string().min(5), safetyScore: z.coerce.number().min(0).max(100).optional(), status: z.nativeEnum(DriverStatus).optional() });
const tripInput = z.object({ source: z.string().min(2), destination: z.string().min(2), vehicleId: z.string().uuid(), driverId: z.string().uuid(), cargoWeightKg: z.coerce.number().positive(), plannedDistance: z.coerce.number().positive() });
const send = (res: any, data: unknown, status = 200) => res.status(status).json({ data });
const id = (value: unknown) => z.string().uuid().parse(value);
const vehicleForTrip = async (tx: Prisma.TransactionClient, vehicleId: string, driverId: string, cargo: number) => {
  const [vehicle, driver] = await Promise.all([tx.vehicle.findUnique({ where: { id: vehicleId } }), tx.driver.findUnique({ where: { id: driverId } })]);
  if (!vehicle || !driver) throw new ApiError(404, 'RESOURCE_NOT_FOUND', 'Vehicle or driver was not found');
  if (vehicle.status !== VehicleStatus.AVAILABLE) throw new ApiError(409, 'VEHICLE_UNAVAILABLE', 'Vehicle is not available');
  if (driver.status !== DriverStatus.AVAILABLE || driver.licenseExpiryDate <= new Date()) throw new ApiError(409, 'DRIVER_UNAVAILABLE', 'Driver is unavailable or has an expired license');
  if (cargo > vehicle.maxLoadCapacityKg) throw new ApiError(400, 'CAPACITY_EXCEEDED', 'Cargo weight exceeds vehicle capacity');
  return { vehicle, driver };
};

// Vehicles
operationsRouter.get('/vehicles', allowRoles(...all), asyncHandler(async (req, res) => send(res, await prisma.vehicle.findMany({ where: { ...(req.query.status ? { status: z.nativeEnum(VehicleStatus).parse(req.query.status) } : {}), ...(req.query.type ? { type: String(req.query.type) } : {}), ...(req.query.region ? { region: String(req.query.region) } : {}) }, orderBy: { createdAt: 'desc' } }))));
operationsRouter.get('/vehicles/available', allowRoles(...all), asyncHandler(async (_req, res) => send(res, await prisma.vehicle.findMany({ where: { status: VehicleStatus.AVAILABLE } }))));
operationsRouter.get('/vehicles/:id', allowRoles(...all), asyncHandler(async (req, res) => { const item = await prisma.vehicle.findUnique({ where: { id: id(req.params.id) } }); if (!item) throw new ApiError(404, 'VEHICLE_NOT_FOUND', 'Vehicle not found'); send(res, item); }));
operationsRouter.post('/vehicles', allowRoles(Role.ADMIN, Role.FLEET_MANAGER), asyncHandler(async (req, res) => send(res, await prisma.vehicle.create({ data: vehicleInput.parse(req.body) }), 201)));
operationsRouter.patch('/vehicles/:id', allowRoles(Role.ADMIN, Role.FLEET_MANAGER), asyncHandler(async (req, res) => send(res, await prisma.vehicle.update({ where: { id: id(req.params.id) }, data: vehicleInput.partial().parse(req.body) }))));
operationsRouter.delete('/vehicles/:id', allowRoles(Role.ADMIN, Role.FLEET_MANAGER), asyncHandler(async (req, res) => send(res, await prisma.vehicle.update({ where: { id: id(req.params.id) }, data: { status: VehicleStatus.RETIRED } }))));

// Drivers
operationsRouter.get('/drivers', allowRoles(...all), asyncHandler(async (req, res) => send(res, await prisma.driver.findMany({ where: req.query.status ? { status: z.nativeEnum(DriverStatus).parse(req.query.status) } : {}, orderBy: { createdAt: 'desc' } }))));
operationsRouter.get('/drivers/available', allowRoles(...all), asyncHandler(async (_req, res) => send(res, await prisma.driver.findMany({ where: { status: DriverStatus.AVAILABLE, licenseExpiryDate: { gt: new Date() } } }))));
operationsRouter.get('/drivers/:id', allowRoles(...all), asyncHandler(async (req, res) => { const item = await prisma.driver.findUnique({ where: { id: id(req.params.id) } }); if (!item) throw new ApiError(404, 'DRIVER_NOT_FOUND', 'Driver not found'); send(res, item); }));
operationsRouter.post('/drivers', allowRoles(Role.ADMIN, Role.SAFETY_OFFICER), asyncHandler(async (req, res) => send(res, await prisma.driver.create({ data: driverInput.parse(req.body) }), 201)));
operationsRouter.patch('/drivers/:id', allowRoles(Role.ADMIN, Role.SAFETY_OFFICER), asyncHandler(async (req, res) => send(res, await prisma.driver.update({ where: { id: id(req.params.id) }, data: driverInput.partial().parse(req.body) }))));

// Trips. Creation checks eligibility but deliberately leaves both resources AVAILABLE until dispatch.
operationsRouter.get('/trips', allowRoles(...all), asyncHandler(async (req, res) => { const where = { ...(req.query.status ? { status: z.nativeEnum(TripStatus).parse(req.query.status) } : {}), ...(req.query.driverId ? { driverId: String(req.query.driverId) } : {}), ...(req.query.vehicleId ? { vehicleId: String(req.query.vehicleId) } : {}) }; send(res, await prisma.trip.findMany({ where, include: { vehicle: true, driver: true }, orderBy: { createdAt: 'desc' } })); }));
operationsRouter.get('/trips/:id', allowRoles(...all), asyncHandler(async (req, res) => { const item = await prisma.trip.findUnique({ where: { id: id(req.params.id) }, include: { vehicle: true, driver: true } }); if (!item) throw new ApiError(404, 'TRIP_NOT_FOUND', 'Trip not found'); send(res, item); }));
operationsRouter.post('/trips', allowRoles(Role.ADMIN, Role.DRIVER), asyncHandler(async (req, res) => { const data = tripInput.parse(req.body); await prisma.$transaction(tx => vehicleForTrip(tx, data.vehicleId, data.driverId, data.cargoWeightKg)); send(res, await prisma.trip.create({ data: { ...data, createdByProfileId: req.user!.id } }), 201); }));
operationsRouter.patch('/trips/:id/dispatch', allowRoles(Role.ADMIN, Role.DRIVER), asyncHandler(async (req, res) => { const tripId = id(req.params.id); const item = await prisma.$transaction(async tx => { const trip = await tx.trip.findUnique({ where: { id: tripId } }); if (!trip) throw new ApiError(404, 'TRIP_NOT_FOUND', 'Trip not found'); if (trip.status !== TripStatus.DRAFT) throw new ApiError(409, 'INVALID_TRIP_STATE', 'Only draft trips can be dispatched'); await vehicleForTrip(tx, trip.vehicleId, trip.driverId, trip.cargoWeightKg); await Promise.all([tx.vehicle.update({ where: { id: trip.vehicleId }, data: { status: VehicleStatus.ON_TRIP } }), tx.driver.update({ where: { id: trip.driverId }, data: { status: DriverStatus.ON_TRIP } })]); return tx.trip.update({ where: { id: tripId }, data: { status: TripStatus.DISPATCHED, dispatchedAt: new Date() } }); }); send(res, item); }));
operationsRouter.patch('/trips/:id/complete', allowRoles(Role.ADMIN, Role.DRIVER), asyncHandler(async (req, res) => { const input = z.object({ actualDistance: z.coerce.number().nonnegative(), fuelConsumedL: z.coerce.number().nonnegative().optional(), fuelCost: z.coerce.number().nonnegative().optional() }).parse(req.body); const tripId = id(req.params.id); const item = await prisma.$transaction(async tx => { const trip = await tx.trip.findUnique({ where: { id: tripId } }); if (!trip) throw new ApiError(404, 'TRIP_NOT_FOUND', 'Trip not found'); if (trip.status !== TripStatus.DISPATCHED) throw new ApiError(409, 'INVALID_TRIP_STATE', 'Only dispatched trips can be completed'); await Promise.all([tx.vehicle.update({ where: { id: trip.vehicleId }, data: { status: VehicleStatus.AVAILABLE, odometerKm: { increment: input.actualDistance } } }), tx.driver.update({ where: { id: trip.driverId }, data: { status: DriverStatus.AVAILABLE } })]); if (input.fuelConsumedL !== undefined) await tx.fuelLog.create({ data: { vehicleId: trip.vehicleId, liters: input.fuelConsumedL, cost: input.fuelCost ?? 0 } }); return tx.trip.update({ where: { id: tripId }, data: { status: TripStatus.COMPLETED, completedAt: new Date(), actualDistance: input.actualDistance, fuelConsumedL: input.fuelConsumedL } }); }); send(res, item); }));
operationsRouter.patch('/trips/:id/cancel', allowRoles(Role.ADMIN, Role.DRIVER), asyncHandler(async (req, res) => { const tripId = id(req.params.id); const item = await prisma.$transaction(async tx => { const trip = await tx.trip.findUnique({ where: { id: tripId } }); if (!trip) throw new ApiError(404, 'TRIP_NOT_FOUND', 'Trip not found'); if (trip.status !== TripStatus.DRAFT && trip.status !== TripStatus.DISPATCHED) throw new ApiError(409, 'INVALID_TRIP_STATE', 'Only draft or dispatched trips can be cancelled'); if (trip.status === TripStatus.DISPATCHED) await Promise.all([tx.vehicle.update({ where: { id: trip.vehicleId }, data: { status: VehicleStatus.AVAILABLE } }), tx.driver.update({ where: { id: trip.driverId }, data: { status: DriverStatus.AVAILABLE } })]); return tx.trip.update({ where: { id: tripId }, data: { status: TripStatus.CANCELLED, cancelledAt: new Date() } }); }); send(res, item); }));

// Maintenance, fuel, and expenses
operationsRouter.get('/maintenance', allowRoles(Role.ADMIN, Role.FLEET_MANAGER), asyncHandler(async (req, res) => send(res, await prisma.maintenanceLog.findMany({ where: { ...(req.query.vehicleId ? { vehicleId: String(req.query.vehicleId) } : {}), ...(req.query.status ? { status: z.nativeEnum(MaintenanceStatus).parse(req.query.status) } : {}) }, include: { vehicle: true } }))));
operationsRouter.post('/maintenance', allowRoles(Role.ADMIN, Role.FLEET_MANAGER), asyncHandler(async (req, res) => { const data = z.object({ vehicleId: z.string().uuid(), description: z.string().min(2), cost: z.coerce.number().min(0).optional() }).parse(req.body); const item = await prisma.$transaction(async tx => { const vehicle = await tx.vehicle.findUnique({ where: { id: data.vehicleId } }); if (!vehicle) throw new ApiError(404, 'VEHICLE_NOT_FOUND', 'Vehicle not found'); if (vehicle.status === VehicleStatus.ON_TRIP || vehicle.status === VehicleStatus.RETIRED) throw new ApiError(409, 'VEHICLE_UNAVAILABLE', 'Vehicle cannot be put into maintenance'); await tx.vehicle.update({ where: { id: data.vehicleId }, data: { status: VehicleStatus.IN_SHOP } }); return tx.maintenanceLog.create({ data }); }); send(res, item, 201); }));
operationsRouter.patch('/maintenance/:id/close', allowRoles(Role.ADMIN, Role.FLEET_MANAGER), asyncHandler(async (req, res) => { const logId = id(req.params.id); const item = await prisma.$transaction(async tx => { const log = await tx.maintenanceLog.findUnique({ where: { id: logId } }); if (!log) throw new ApiError(404, 'MAINTENANCE_NOT_FOUND', 'Maintenance record not found'); if (log.status !== MaintenanceStatus.OPEN) throw new ApiError(409, 'INVALID_MAINTENANCE_STATE', 'Maintenance record is already closed'); const vehicle = await tx.vehicle.findUniqueOrThrow({ where: { id: log.vehicleId } }); if (vehicle.status !== VehicleStatus.RETIRED) await tx.vehicle.update({ where: { id: log.vehicleId }, data: { status: VehicleStatus.AVAILABLE } }); return tx.maintenanceLog.update({ where: { id: logId }, data: { status: MaintenanceStatus.CLOSED, closedAt: new Date() } }); }); send(res, item); }));
operationsRouter.get('/fuel-logs', allowRoles(Role.ADMIN, Role.FINANCIAL_ANALYST, Role.FLEET_MANAGER, Role.DRIVER), asyncHandler(async (req, res) => send(res, await prisma.fuelLog.findMany({ where: req.query.vehicleId ? { vehicleId: String(req.query.vehicleId) } : {}, include: { vehicle: true } }))));
operationsRouter.post('/fuel-logs', allowRoles(Role.ADMIN, Role.FLEET_MANAGER, Role.DRIVER), asyncHandler(async (req, res) => send(res, await prisma.fuelLog.create({ data: z.object({ vehicleId: z.string().uuid(), liters: z.coerce.number().positive(), cost: z.coerce.number().min(0), date: z.coerce.date().optional() }).parse(req.body) }), 201)));
operationsRouter.get('/expenses', allowRoles(Role.ADMIN, Role.FINANCIAL_ANALYST, Role.FLEET_MANAGER, Role.DRIVER), asyncHandler(async (req, res) => send(res, await prisma.expense.findMany({ where: { ...(req.query.vehicleId ? { vehicleId: String(req.query.vehicleId) } : {}), ...(req.query.type ? { type: z.nativeEnum(ExpenseType).parse(req.query.type) } : {}) }, include: { vehicle: true } }))));
operationsRouter.post('/expenses', allowRoles(Role.ADMIN, Role.FLEET_MANAGER, Role.DRIVER), asyncHandler(async (req, res) => send(res, await prisma.expense.create({ data: z.object({ vehicleId: z.string().uuid(), type: z.nativeEnum(ExpenseType), amount: z.coerce.number().positive(), note: z.string().max(500).optional(), date: z.coerce.date().optional() }).parse(req.body) }), 201)));
operationsRouter.get('/vehicles/:id/total-cost', allowRoles(...all), asyncHandler(async (req, res) => { const vehicleId = id(req.params.id); const [fuel, maintenance, expenses] = await Promise.all([prisma.fuelLog.aggregate({ where: { vehicleId }, _sum: { cost: true } }), prisma.maintenanceLog.aggregate({ where: { vehicleId }, _sum: { cost: true } }), prisma.expense.aggregate({ where: { vehicleId }, _sum: { amount: true } })]); send(res, { vehicleId, fuelCost: fuel._sum.cost ?? 0, maintenanceCost: maintenance._sum.cost ?? 0, expenseCost: expenses._sum.amount ?? 0, totalCost: (fuel._sum.cost ?? 0) + (maintenance._sum.cost ?? 0) + (expenses._sum.amount ?? 0) }); }));

operationsRouter.get('/dashboard/kpis', allowRoles(...all), asyncHandler(async (_req, res) => { const [availableVehicles, activeVehicles, inShopVehicles, activeTrips, draftTrips, driversOnDuty, totalFleet] = await Promise.all([prisma.vehicle.count({ where: { status: VehicleStatus.AVAILABLE } }), prisma.vehicle.count({ where: { status: VehicleStatus.ON_TRIP } }), prisma.vehicle.count({ where: { status: VehicleStatus.IN_SHOP } }), prisma.trip.count({ where: { status: TripStatus.DISPATCHED } }), prisma.trip.count({ where: { status: TripStatus.DRAFT } }), prisma.driver.count({ where: { status: DriverStatus.ON_TRIP } }), prisma.vehicle.count({ where: { status: { not: VehicleStatus.RETIRED } } })]); send(res, { activeVehicles, availableVehicles, inMaintenanceVehicles: inShopVehicles, activeTrips, pendingTrips: draftTrips, driversOnDuty, fleetUtilizationPercent: totalFleet ? Number(((activeVehicles / totalFleet) * 100).toFixed(2)) : 0 }); }));
operationsRouter.get('/reports/fuel-efficiency', allowRoles(Role.ADMIN, Role.FINANCIAL_ANALYST, Role.FLEET_MANAGER), asyncHandler(async (req, res) => { const trips = await prisma.trip.findMany({ where: { status: TripStatus.COMPLETED, ...(req.query.vehicleId ? { vehicleId: String(req.query.vehicleId) } : {}) }, select: { vehicleId: true, actualDistance: true, fuelConsumedL: true } }); const result = Object.values(trips.reduce<Record<string, { vehicleId: string; distanceKm: number; fuelLiters: number }>>((acc, trip) => { const entry = acc[trip.vehicleId] ??= { vehicleId: trip.vehicleId, distanceKm: 0, fuelLiters: 0 }; entry.distanceKm += trip.actualDistance ?? 0; entry.fuelLiters += trip.fuelConsumedL ?? 0; return acc; }, {})).map(item => ({ ...item, kmPerLiter: item.fuelLiters ? Number((item.distanceKm / item.fuelLiters).toFixed(2)) : null })); send(res, result); }));
operationsRouter.get('/reports/fleet-utilization', allowRoles(Role.ADMIN, Role.FINANCIAL_ANALYST, Role.FLEET_MANAGER), asyncHandler(async (_req, res) => { const [active, total] = await Promise.all([prisma.vehicle.count({ where: { status: VehicleStatus.ON_TRIP } }), prisma.vehicle.count({ where: { status: { not: VehicleStatus.RETIRED } } })]); send(res, { activeVehicles: active, totalEligibleVehicles: total, utilizationPercent: total ? Number(((active / total) * 100).toFixed(2)) : 0 }); }));
operationsRouter.get('/reports/operational-cost', allowRoles(Role.ADMIN, Role.FINANCIAL_ANALYST, Role.FLEET_MANAGER), asyncHandler(async (req, res) => { const vehicleId = req.query.vehicleId ? String(req.query.vehicleId) : undefined; const [fuel, maintenance, expenses] = await Promise.all([prisma.fuelLog.aggregate({ where: vehicleId ? { vehicleId } : {}, _sum: { cost: true } }), prisma.maintenanceLog.aggregate({ where: vehicleId ? { vehicleId } : {}, _sum: { cost: true } }), prisma.expense.aggregate({ where: vehicleId ? { vehicleId } : {}, _sum: { amount: true } })]); send(res, { vehicleId: vehicleId ?? null, fuelCost: fuel._sum.cost ?? 0, maintenanceCost: maintenance._sum.cost ?? 0, expensesCost: expenses._sum.amount ?? 0, totalOperationalCost: (fuel._sum.cost ?? 0) + (maintenance._sum.cost ?? 0) + (expenses._sum.amount ?? 0) }); }));
